name: Publish package to GitHub Packages
on:
  pull_request:
    types: [opened, synchronize]
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - id: github-app-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.JSONPATHCOMPILER_GITHUB_APP_APP_ID }}
          private_key: ${{ secrets.JSONPATHCOMPILER_GITHUB_APP_PRIVATE_KEY }}
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ steps.github-app-token.outputs.token }}
